/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.itson.zapateria.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import mx.itson.zapateria.persistencia.ApartadoDAO;
import mx.itson.zapateria.persistencia.ProveedorDAO;
import static mx.itson.zapateria.ui.Main.pnlAnadir;
import static mx.itson.zapateria.ui.Main.pnlApartados;
import static mx.itson.zapateria.ui.Main.pnlBuscar;
import static mx.itson.zapateria.ui.Main.pnlInicio;
import static mx.itson.zapateria.ui.Main.pnlJFrames;
import static mx.itson.zapateria.ui.Main.pnlProveedor;
import static mx.itson.zapateria.ui.Main.pnlVendido;

/**
 *
 * @author chiqu
 */
public class AbonarApartado extends javax.swing.JPanel {

    /**
     * Creates new form NuevoApartado
     */
    public AbonarApartado() {
        initComponents();
        inicio();
        List<String> valores = ProveedorDAO.obtenerValoresColumna("nombre");

        for (String valor : valores) {
            cbxProveedor.addItem(valor);
        }
    }

    public void inicio(){
        int filaSeleccionada = Apartados.tblApartados.getSelectedRow();
        int codigo = Integer.parseInt(Apartados.tblApartados.getValueAt(filaSeleccionada, 2).toString());
        
        String nombre = Apartados.tblApartados.getValueAt(filaSeleccionada, 0).toString();
        String celular = Apartados.tblApartados.getValueAt(filaSeleccionada, 1).toString();;
        String codigotxf = Apartados.tblApartados.getValueAt(filaSeleccionada, 2).toString();;
        
        String color = Apartados.tblApartados.getValueAt(filaSeleccionada, 3).toString().toLowerCase();
        color = Character.toUpperCase(color.charAt(0)) + color.substring(1);
        
        String numero = Apartados.tblApartados.getValueAt(filaSeleccionada, 4).toString();
            if (numero.endsWith(".0")) { // Si el número es un entero, terminará con ".0"
                numero = numero.substring(0, numero.length() - 2); // Eliminar ".0" al final
            }
        
        String tipo = Apartados.tblApartados.getValueAt(filaSeleccionada, 5).toString().toLowerCase(); 
        tipo = Character.toUpperCase(tipo.charAt(0)) + tipo.substring(1);
        if(tipo.equals("Botatrabajo")){
            tipo = "Bota de trabajo";
        }else if(tipo.equals("Botarodeo")){
            tipo = "Bota de rodeo";
        }else if(tipo.equals("Botaalta")){
            tipo = "Bota alta";
        }
        
        String sexo = Apartados.tblApartados.getValueAt(filaSeleccionada, 6).toString().toLowerCase();
        sexo = Character.toUpperCase(sexo.charAt(0)) + sexo.substring(1);
        
        String precio = Apartados.tblApartados.getValueAt(filaSeleccionada, 7).toString().substring(1);
        String estilo = Apartados.tblApartados.getValueAt(filaSeleccionada, 9).toString();
        String numeroApartado = Apartados.tblApartados.getValueAt(filaSeleccionada, 12).toString().substring(1);
        String proveedor = Apartados.tblApartados.getValueAt(filaSeleccionada, 13).toString();
        
        txfNombre.setText(nombre);
        txfCelular.setText(celular);
        txfCodigo.setText(codigotxf);
        txfColor.setText(color);
        cbxNumero.setSelectedItem(numero);
        cbxTipo.setSelectedItem(tipo);
        cbxSexo.setSelectedItem(sexo);
        txfPrecio.setText(precio);
        txfEstilo.setText(estilo);
        txfNumeroApartado.setText(numeroApartado);
        cbxProveedor.setSelectedItem(proveedor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txfNombre = new com.raven.zapateria.textfield.TextField();
        jLabel2 = new javax.swing.JLabel();
        txfCelular = new com.raven.zapateria.textfield.TextField();
        jLabel3 = new javax.swing.JLabel();
        txfCodigo = new com.raven.zapateria.textfield.TextField();
        jLabel4 = new javax.swing.JLabel();
        txfColor = new com.raven.zapateria.textfield.TextField();
        jLabel5 = new javax.swing.JLabel();
        txfColor1 = new com.raven.zapateria.textfield.TextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxNumero = new com.raven.zapateria.combobox.Combobox();
        jLabel8 = new javax.swing.JLabel();
        cbxTipo = new com.raven.zapateria.combobox.Combobox();
        jLabel9 = new javax.swing.JLabel();
        cbxSexo = new com.raven.zapateria.combobox.Combobox();
        jLabel10 = new javax.swing.JLabel();
        txfPrecio = new com.raven.zapateria.textfield.TextField();
        jLabel12 = new javax.swing.JLabel();
        txfRestante = new com.raven.zapateria.textfield.TextField();
        jLabel13 = new javax.swing.JLabel();
        txfEstilo = new com.raven.zapateria.textfield.TextField();
        pnlGuardar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txfNumeroApartado = new com.raven.zapateria.textfield.TextField();
        cbxProveedor = new com.raven.zapateria.combobox.Combobox();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1510, 770));
        setMinimumSize(new java.awt.Dimension(1510, 770));
        setPreferredSize(new java.awt.Dimension(1510, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo apartado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/zapateria/imagenes/Logo Zapateria Von 340x191.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 310, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 210, 20));

        txfNombre.setEditable(false);
        txfNombre.setCaretColor(new java.awt.Color(0, 0, 0));
        txfNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfNombre.setLabelText("");
        txfNombre.setLineColor(new java.awt.Color(73, 150, 50));
        txfNombre.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 200, 30));

        txfCelular.setEditable(false);
        txfCelular.setCaretColor(new java.awt.Color(0, 0, 0));
        txfCelular.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfCelular.setLabelText("");
        txfCelular.setLineColor(new java.awt.Color(73, 150, 50));
        txfCelular.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Celular");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 200, 30));

        txfCodigo.setEditable(false);
        txfCodigo.setCaretColor(new java.awt.Color(0, 0, 0));
        txfCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfCodigo.setLabelText("");
        txfCodigo.setLineColor(new java.awt.Color(73, 150, 50));
        txfCodigo.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Codigo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 200, 40));

        txfColor.setEditable(false);
        txfColor.setCaretColor(new java.awt.Color(0, 0, 0));
        txfColor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfColor.setLabelText("");
        txfColor.setLineColor(new java.awt.Color(73, 150, 50));
        txfColor.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Color");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 200, 40));

        txfColor1.setCaretColor(new java.awt.Color(0, 0, 0));
        txfColor1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfColor1.setLabelText("");
        txfColor1.setLineColor(new java.awt.Color(73, 150, 50));
        txfColor1.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 230, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Color");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 200, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Numero");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 120, 30));

        cbxNumero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "10.5", "11", "11.5", "12", "12.5", "13", "13.5", "14", "14.5", "15", "15.5", "16", "16.5", "17", "17.5", "18", "18.5", "19", "19.5", "20", "20.5", "21", "21.5", "22", "22.5", "23", "23.5", "24", "24.5", "25", "25.5", "26", "26.5", "27", "27.5", "28", "28.5", "29", "29.5", "30", "30.5" }));
        cbxNumero.setSelectedIndex(-1);
        cbxNumero.setEnabled(false);
        cbxNumero.setLabeText("");
        cbxNumero.setLineColor(new java.awt.Color(73, 150, 50));
        cbxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNumeroActionPerformed(evt);
            }
        });
        add(cbxNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 230, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tipo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 110, 30));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teni", "Zapato", "Zapatilla", "Huarache", "Taquete", "Bota de trabajo", "Bota de rodeo", "Bota alta", "Botin", "Reloj" }));
        cbxTipo.setSelectedIndex(-1);
        cbxTipo.setEnabled(false);
        cbxTipo.setLabeText("");
        cbxTipo.setLineColor(new java.awt.Color(73, 150, 50));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });
        add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 230, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Sexo");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 60, 20));

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mujer", "Hombre", "Unisex" }));
        cbxSexo.setSelectedIndex(-1);
        cbxSexo.setEnabled(false);
        cbxSexo.setLabeText("");
        cbxSexo.setLineColor(new java.awt.Color(73, 150, 50));
        cbxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoActionPerformed(evt);
            }
        });
        add(cbxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 230, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Precio");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 100, 30));

        txfPrecio.setEditable(false);
        txfPrecio.setCaretColor(new java.awt.Color(0, 0, 0));
        txfPrecio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfPrecio.setLabelText("");
        txfPrecio.setLineColor(new java.awt.Color(73, 150, 50));
        txfPrecio.setSelectionColor(new java.awt.Color(73, 150, 50));
        txfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPrecioActionPerformed(evt);
            }
        });
        add(txfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 230, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Restante");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 310, 100, 30));

        txfRestante.setCaretColor(new java.awt.Color(0, 0, 0));
        txfRestante.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfRestante.setLabelText("");
        txfRestante.setLineColor(new java.awt.Color(73, 150, 50));
        txfRestante.setSelectionColor(new java.awt.Color(73, 150, 50));
        txfRestante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfRestanteActionPerformed(evt);
            }
        });
        add(txfRestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 340, 230, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Estilo");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 210, 90, 30));

        txfEstilo.setEditable(false);
        txfEstilo.setCaretColor(new java.awt.Color(0, 0, 0));
        txfEstilo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfEstilo.setLabelText("");
        txfEstilo.setLineColor(new java.awt.Color(73, 150, 50));
        txfEstilo.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 240, 230, -1));

        pnlGuardar.setBackground(new java.awt.Color(73, 150, 50));
        pnlGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGuardarMouseExited(evt);
            }
        });
        pnlGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Guardar");
        pnlGuardar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 70));

        add(pnlGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, 230, 70));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Numero de apartado");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 410, 250, 30));

        txfNumeroApartado.setEditable(false);
        txfNumeroApartado.setCaretColor(new java.awt.Color(0, 0, 0));
        txfNumeroApartado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfNumeroApartado.setLabelText("");
        txfNumeroApartado.setLineColor(new java.awt.Color(73, 150, 50));
        txfNumeroApartado.setSelectionColor(new java.awt.Color(73, 150, 50));
        txfNumeroApartado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNumeroApartadoActionPerformed(evt);
            }
        });
        add(txfNumeroApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 440, 230, -1));

        cbxProveedor.setLabeText("");
        cbxProveedor.setLineColor(new java.awt.Color(73, 150, 50));
        cbxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProveedorActionPerformed(evt);
            }
        });
        add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 540, 230, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Proveedor");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, 240, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNumeroActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void cbxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoActionPerformed

    private void txfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPrecioActionPerformed

    private void txfRestanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfRestanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfRestanteActionPerformed

    private void pnlGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGuardarMouseClicked

        int filaSeleccionada = Apartados.tblApartados.getSelectedRow();
        int codigo = Integer.parseInt(Apartados.tblApartados.getValueAt(filaSeleccionada, 2).toString());
        
        String restante = txfRestante.getText();
        String numeroApartado = Apartados.tblApartados.getValueAt(filaSeleccionada, 12).toString();
        
        try {
            if (ApartadoDAO.editar(Double.parseDouble(restante), codigo)) {
                    JOptionPane.showMessageDialog(null, "Se ha abonado al apartado " +numeroApartado);

                    Apartados p3 = new Apartados();
                    p3.setSize(1510, 770);
                    p3.setLocation(0, 0);

                    setColor(pnlApartados);
                    resetColor(pnlVendido);
                    resetColor(pnlAnadir);
                    resetColor(pnlInicio);
                    resetColor(pnlBuscar);
                    resetColor(pnlProveedor);

                    pnlJFrames.removeAll();
                    pnlJFrames.add(p3, BorderLayout.CENTER);
                    pnlJFrames.revalidate();
                    pnlJFrames.repaint();
                    
                }
        } catch (Exception e) {
            System.out.println("Error al guardar " + e);
        }
        
    }//GEN-LAST:event_pnlGuardarMouseClicked

    private void pnlGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGuardarMouseEntered

        pnlGuardar.setBackground(new Color(38, 109, 43));
    }//GEN-LAST:event_pnlGuardarMouseEntered

    private void pnlGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGuardarMouseExited

        pnlGuardar.setBackground(new Color(73, 150, 50));
    }//GEN-LAST:event_pnlGuardarMouseExited

    private void txfNumeroApartadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNumeroApartadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNumeroApartadoActionPerformed

    private void cbxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProveedorActionPerformed

    public void setColor(JPanel panel) {
        panel.setBackground(new Color(73, 150, 50));
    }

    /**
     * Establece un panel del color rgb que pongamos Se ultilizará para cuando
     * se deje de seleccionar un panel del menú en el ui principal
     *
     * @param panel Nombre del panel que queramos establecerle el color
     */
    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(38, 109, 43));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.raven.zapateria.combobox.Combobox cbxNumero;
    private com.raven.zapateria.combobox.Combobox cbxProveedor;
    public static com.raven.zapateria.combobox.Combobox cbxSexo;
    public static com.raven.zapateria.combobox.Combobox cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlGuardar;
    public static com.raven.zapateria.textfield.TextField txfCelular;
    public static com.raven.zapateria.textfield.TextField txfCodigo;
    public static com.raven.zapateria.textfield.TextField txfColor;
    private com.raven.zapateria.textfield.TextField txfColor1;
    public static com.raven.zapateria.textfield.TextField txfEstilo;
    public static com.raven.zapateria.textfield.TextField txfNombre;
    public static com.raven.zapateria.textfield.TextField txfNumeroApartado;
    public static com.raven.zapateria.textfield.TextField txfPrecio;
    public static com.raven.zapateria.textfield.TextField txfRestante;
    // End of variables declaration//GEN-END:variables
}
