/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.itson.zapateria.ui;

import java.awt.Color;

/**
 *
 * @author chiqu
 */
public class Apartado extends javax.swing.JPanel {

    /**
     * Creates new form Apartado
     */
    public Apartado() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblApartados = new javax.swing.JTable();
        pnlApartar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlApartar1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1510, 770));
        setMinimumSize(new java.awt.Dimension(1510, 770));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1510, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblApartados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Celular", "Codigo", "Color", "Numero", "Tipo", "Sexo", "Precio", "Estilo", "Fecha de apartado", "Fecha de vencimiento", "Numero de apartado"
            }
        ));
        jScrollPane1.setViewportView(tblApartados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 1380, 500));

        pnlApartar.setBackground(new java.awt.Color(73, 150, 50));
        pnlApartar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlApartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlApartarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlApartarMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Abonar o liquidar");

        javax.swing.GroupLayout pnlApartarLayout = new javax.swing.GroupLayout(pnlApartar);
        pnlApartar.setLayout(pnlApartarLayout);
        pnlApartarLayout.setHorizontalGroup(
            pnlApartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApartarLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlApartarLayout.setVerticalGroup(
            pnlApartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApartarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pnlApartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, 220, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/zapateria/imagenes/Logo Zapateria Von 340x191.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 310, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Apartados");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 59));

        pnlApartar1.setBackground(new java.awt.Color(73, 150, 50));
        pnlApartar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlApartar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlApartar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlApartar1MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nuevo apartado");

        javax.swing.GroupLayout pnlApartar1Layout = new javax.swing.GroupLayout(pnlApartar1);
        pnlApartar1.setLayout(pnlApartar1Layout);
        pnlApartar1Layout.setHorizontalGroup(
            pnlApartar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlApartar1Layout.setVerticalGroup(
            pnlApartar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(pnlApartar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 220, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlApartarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApartarMouseEntered
        pnlApartar.setBackground(new Color(38,109,43));
    }//GEN-LAST:event_pnlApartarMouseEntered

    private void pnlApartarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApartarMouseExited
        pnlApartar.setBackground(new Color(73,150,50));
    }//GEN-LAST:event_pnlApartarMouseExited

    private void pnlApartar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApartar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlApartar1MouseEntered

    private void pnlApartar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApartar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlApartar1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlApartar;
    private javax.swing.JPanel pnlApartar1;
    private javax.swing.JTable tblApartados;
    // End of variables declaration//GEN-END:variables
}
