/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.itson.zapateria.ui;

/**
 *
 * @author chiqu
 */
public class NuevoApartado extends javax.swing.JPanel {

    /**
     * Creates new form NuevoApartado
     */
    public NuevoApartado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txfNombre = new com.raven.zapateria.textfield.TextField();
        jLabel2 = new javax.swing.JLabel();
        txfCelular = new com.raven.zapateria.textfield.TextField();
        jLabel3 = new javax.swing.JLabel();
        txfCodigo = new com.raven.zapateria.textfield.TextField();
        jLabel4 = new javax.swing.JLabel();
        txfColor = new com.raven.zapateria.textfield.TextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1510, 770));
        setMinimumSize(new java.awt.Dimension(1510, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo apartado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/zapateria/imagenes/Logo Zapateria Von 340x191.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 310, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 210, 10));

        txfNombre.setCaretColor(new java.awt.Color(0, 0, 0));
        txfNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfNombre.setLabelText("");
        txfNombre.setLineColor(new java.awt.Color(73, 150, 50));
        txfNombre.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 200, 30));

        txfCelular.setCaretColor(new java.awt.Color(0, 0, 0));
        txfCelular.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfCelular.setLabelText("");
        txfCelular.setLineColor(new java.awt.Color(73, 150, 50));
        txfCelular.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Celular");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, 30));

        txfCodigo.setCaretColor(new java.awt.Color(0, 0, 0));
        txfCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfCodigo.setLabelText("");
        txfCodigo.setLineColor(new java.awt.Color(73, 150, 50));
        txfCodigo.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Codigo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 200, 40));

        txfColor.setCaretColor(new java.awt.Color(0, 0, 0));
        txfColor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txfColor.setLabelText("");
        txfColor.setLineColor(new java.awt.Color(73, 150, 50));
        txfColor.setSelectionColor(new java.awt.Color(73, 150, 50));
        add(txfColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Color");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 200, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private com.raven.zapateria.textfield.TextField txfCelular;
    private com.raven.zapateria.textfield.TextField txfCodigo;
    private com.raven.zapateria.textfield.TextField txfColor;
    private com.raven.zapateria.textfield.TextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
